<a href="https://colab.research.google.com/github/ElenaBara21/data_analyses-u-/blob/main/NumPy_Indexing_and_Selection.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Indexing and Selection**

* Grabbing single element
* Grabbing a slice of elements
* Broadcasting selections
* Indexing and selection in 2-dimensions
* Conditional selection

In [ ]:
import numpy as np
arr = np.arange(0, 11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
arr[8]

8

In [ ]:
arr[0:5]=100
arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [ ]:
arr = np.arange(0,11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
slice_of_arr = arr[0:5]
slice_of_arr

array([0, 1, 2, 3, 4])

In [ ]:
slice_of_arr[:]=99 #Broadcasting
slice_of_arr

array([99, 99, 99, 99, 99])

In [ ]:
arr_copy = arr.copy()
arr_copy[:] = 100
arr_copy

array([100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100])

In [ ]:
arr

array([99, 99, 99, 99, 99,  5,  6,  7,  8,  9, 10])

In [ ]:
arr_2d = np.array([[5,10,15],[20,25,30],[35,40,45]]) #2dimensional array bcs 012 rows, but shape 3x3
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [ ]:
arr_2d.shape

(3, 3)

In [ ]:
arr_2d[2]

array([35, 40, 45])

In [ ]:
arr_2d[0,2]
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [ ]:
arr_2d[:2]

array([[ 5, 10, 15],
       [20, 25, 30]])

In [ ]:
arr_2d[:2,1:]

array([[10, 15],
       [25, 30]])

In [ ]:
arr=np.arange(1,11)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
arr > 4 #starting from >4 is true

array([False, False, False, False,  True,  True,  True,  True,  True,
        True])

In [ ]:
bool_arr = arr>4
bool_arr

array([False, False, False, False,  True,  True,  True,  True,  True,
        True])

In [ ]:
arr[bool_arr]

array([ 5,  6,  7,  8,  9, 10])

In [ ]:
import numpy as np
dice_rolls = np.array([3, 1, 5, 2, 5, 1, 1, 5, 1, 4, 2, 1, 4, 5, 3, 4, 5, 2, 4, 2, 6, 6, 3, 6, 2, 3, 5, 6, 5])
total_dice_rolls = len(dice_rolls[dice_rolls>2])
total_dice_rolls


19

In [ ]:
dice_rolls[dice_rolls>2]

array([], dtype=bool)

**NumPy Operations**

In [ ]:
import numpy as np


In [ ]:
arr = np.arange(0,10)
arr


array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
arr = arr + 5
arr

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [ ]:
arr = arr + arr
arr

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28])

In [ ]:
arr = arr * arr
arr

array([100, 144, 196, 256, 324, 400, 484, 576, 676, 784])

In [ ]:
arr = arr / arr
arr

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [ ]:
np.sqrt(arr)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [ ]:
np.log(arr)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [ ]:
arr.mean()

1.0

In [ ]:
arr.max()

1.0

In [ ]:
arr2d=np.arange(0,25).reshape(5,5)
arr2d

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [ ]:
arr2d.shape

(5, 5)

In [ ]:
arr2d.sum()

300

In [ ]:
arr2d.sum(axis=0) #это суммы в колонке 0+5+10+15+20 operation accross

array([50, 55, 60, 65, 70])

In [ ]:
arr2d.sum(axis=1) #это суммы в ряду 0+1+2+3+4 = 10

array([ 10,  35,  60,  85, 110])

In [ ]:

import numpy as np
account_transactions = np.array([100,-200,300,-400,100,100,-230,450,500,2000])

account_total =  account_transactions.sum()
account_total

2720