<a href="https://colab.research.google.com/github/ElenaBara21/data_analyses-u-/blob/main/NumPy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## What is NumPy
* Python library for creating N-dimensional arrays
* Ability to quickly broadcast functions
* Built-in linear algebra, statistical distributions, trigonometric, and random number capabilities

**NumPy Arrays**

In [1]:
import numpy as np


list

In [2]:
mylist = [1,2,3]
type(mylist)

list

In [3]:
np.array(mylist)

array([1, 2, 3])

In [4]:
mylist

[1, 2, 3]

In [5]:
myarr = np.array(mylist)
myarr

array([1, 2, 3])

In [6]:
type(myarr)

numpy.ndarray

In [7]:
my_matrix = [[1,2,3],[4,5,6],[7,8,9]] 

In [8]:
my_matrix

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [9]:
np.array(my_matrix)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [12]:
np.arange(0,101,2)

array([  0,   2,   4,   6,   8,  10,  12,  14,  16,  18,  20,  22,  24,
        26,  28,  30,  32,  34,  36,  38,  40,  42,  44,  46,  48,  50,
        52,  54,  56,  58,  60,  62,  64,  66,  68,  70,  72,  74,  76,
        78,  80,  82,  84,  86,  88,  90,  92,  94,  96,  98, 100])

In [15]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [17]:
np.zeros((5,3)) #define by number of rows first, number of columns 2

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [18]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [22]:
np.linspace(0, 10, 11) #where 0 to 10 is interval, where 11 is quantity of number we want

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

identity metrics(known as square metrics)

In [23]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [27]:
np.random.rand(5,2)

array([[0.54740338, 0.8333344 ],
       [0.33636984, 0.10510489],
       [0.70816027, 0.24242783],
       [0.70186163, 0.46155206],
       [0.61587631, 0.26674724]])

In [30]:
np.random.randn(2,3)

array([[ 0.6454361 , -1.36069138,  0.18130443],
       [ 0.1868159 , -1.00135934, -0.65042666]])

In [33]:
np.random.randint(0,101,(4,5))

array([[83, 99, 47, 37, 80],
       [53, 78, 40, 98, 45],
       [65, 23, 15, 16, 41],
       [14, 63, 36, 61, 15]])

In [34]:
np.random.seed(42)
np.random.rand(4)

array([0.37454012, 0.95071431, 0.73199394, 0.59865848])

In [41]:
arr = np.arange(0,30)
arr.reshape(5,6) #должно быть столько жк сколько и вверху например 30 расклад как 5 и 6

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29]])

In [42]:
ranarr = np.random.randint(0,101, 10)
ranarr

array([82, 86, 74, 74, 87, 99, 23,  2, 21, 52])

In [43]:
ranarr.max()

99

In [44]:
ranarr.min()

2

In [45]:
ranarr.argmax() #это положение макс числа 99 - 0,1,2,3,4,5 5 позиция

5

In [46]:
ranarr.argmin() #это положение макс числа 99 - 0,1,2,3,4,5,6,7 7 позиция

7

In [47]:
ranarr.dtype #how much percicion holding your computer

dtype('int64')

In [48]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [49]:
arr.shape

(30,)

In [52]:
arr = arr.reshape(5,6)
arr

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29]])

In [56]:
arr.reshape(30,1)

array([[ 0],
       [ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12],
       [13],
       [14],
       [15],
       [16],
       [17],
       [18],
       [19],
       [20],
       [21],
       [22],
       [23],
       [24],
       [25],
       [26],
       [27],
       [28],
       [29]])